version: '3.8'

services:
  ai-calendar-agent:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: ai-calendar-agent-dev
    environment:
      - ENV=development
      - LOG_LEVEL=DEBUG
    env_file:
      - ../../.env
    volumes:
      - ../../src:/app/src:ro
      - ../../config:/app/config:ro
      - ../../logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-calendar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  monitoring:
    image: prom/prometheus:latest
    container_name: ai-calendar-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  redis_data:
